#!/usr/bin/env python3
"""
LILJR AUTO_CODER v1.0
Self-writing, self-reading, self-healing code.
Writes Python, HTML, CSS, JS. Fixes itself.
No human needed.
"""
import os, sys, json, re, time, traceback, hashlib, inspect

class AutoCoder:
    def __init__(self, base_path):
        self.base = os.path.expanduser(base_path)
        os.makedirs(self.base, exist_ok=True)
        self.logs = []
    
    def log(self, msg):
        entry = f"[{time.strftime('%H:%M:%S')}] {msg}"
        self.logs.append(entry)
        print(f"[AUTOCODER] {entry}")
    
    # ─── FILE OPERATIONS ───
    def read_file(self, path):
        full = os.path.join(self.base, path)
        try:
            with open(full, 'r') as f:
                return f.read()
        except:
            return None
    
    def write_file(self, path, content):
        full = os.path.join(self.base, path)
        os.makedirs(os.path.dirname(full) or '.', exist_ok=True)
        with open(full, 'w') as f:
            f.write(content)
        self.log(f"Wrote {len(content)} chars to {path}")
        return {"status": "written", "path": path, "size": len(content)}
    
    def list_files(self, pattern='.*'):
        files = []
        for root, _, filenames in os.walk(self.base):
            for f in filenames:
                rel = os.path.relpath(os.path.join(root, f), self.base)
                if re.match(pattern, rel):
                    files.append(rel)
        return files
    
    # ─── CODE ANALYSIS ───
    def analyze_file(self, path):
        content = self.read_file(path)
        if not content:
            return {"error": "File not found"}
        
        analysis = {
            "path": path,
            "size": len(content),
            "lines": content.count('\n') + 1,
            "functions": re.findall(r'def\s+(\w+)\s*\(', content),
            "classes": re.findall(r'class\s+(\w+)', content),
            "imports": re.findall(r'(?:import|from)\s+([\w.]+)', content),
            "has_main": '__main__' in content,
            "todo_count": content.lower().count('todo'),
            "fixme_count": content.lower().count('fixme')
        }
        return analysis
    
    def find_issues(self, path):
        content = self.read_file(path)
        if not content:
            return []
        
        issues = []
        lines = content.split('\n')
        for i, line in enumerate(lines, 1):
            if 'FIXME' in line or 'TODO' in line:
                issues.append({"line": i, "issue": line.strip(), "type": "todo"})
            if 'except:' in line and 'pass' in line:
                issues.append({"line": i, "issue": "Bare except:pass", "type": "bug"})
            if 'print(' in line and 'def ' not in line:
                issues.append({"line": i, "issue": "Debug print", "type": "cleanup"})
        return issues
    
    # ─── CODE GENERATION ───
    def generate_python_module(self, name, purpose, functions):
        """Generate a complete Python module."""
        code = f'''#!/usr/bin/env python3
"""
{name.upper()} — Auto-generated by LilJR AutoCoder
Purpose: {purpose}
Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}
"""

'''
        for func_name, desc, params, body in functions:
            param_str = ', '.join([f'{p[0]}={p[1]}' if len(p) > 1 else p[0] for p in params])
            code += f"def {func_name}({param_str}):\n"
            code += f'    """{desc}"""\n'
            for line in body:
                code += f"    {line}\n"
            code += "\n"
        
        code += f'''
if __name__ == '__main__':
    print("[EMPIRE] {name} module ready")
'''
        return code
    
    def generate_html_page(self, title, sections, style='dark'):
        """Generate a complete HTML page."""
        if style == 'dark':
            css = '''
        body { font-family: system-ui, sans-serif; margin: 0; padding: 0; background: #0a0a0a; color: #e0e0e0; }
        .container { max-width: 1200px; margin: 0 auto; padding: 40px 20px; }
        h1 { font-size: 3em; background: linear-gradient(90deg, #00f0ff, #7000ff); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
        .card { background: #111; border: 1px solid #222; border-radius: 12px; padding: 24px; margin: 16px 0; }
        .btn { display: inline-block; padding: 12px 32px; background: #00f0ff; color: #000; text-decoration: none; border-radius: 8px; font-weight: bold; }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }
        @media (max-width: 600px) { h1 { font-size: 2em; } .grid { grid-template-columns: 1fr; } }
'''
        else:
            css = '''
        body { font-family: system-ui, sans-serif; margin: 0; padding: 0; background: #fff; color: #111; }
        .container { max-width: 1200px; margin: 0 auto; padding: 40px 20px; }
        h1 { font-size: 3em; color: #111; }
        .card { background: #f5f5f5; border: 1px solid #ddd; border-radius: 12px; padding: 24px; margin: 16px 0; }
        .btn { display: inline-block; padding: 12px 32px; background: #111; color: #fff; text-decoration: none; border-radius: 8px; }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }
'''
        
        sections_html = ''
        for section in sections:
            stype = section.get('type', 'text')
            if stype == 'hero':
                sections_html += f'''
        <div style="text-align: center; padding: 80px 20px;">
            <h1>{section.get('title', 'Empire')}</h1>
            <p style="font-size: 1.2em; max-width: 600px; margin: 20px auto;">{section.get('text', '')}</p>
            <a href="{section.get('cta_link', '#')}" class="btn">{section.get('cta', 'Get Started')}</a>
        </div>
'''
            elif stype == 'features':
                features = section.get('items', [])
                cards = ''.join([f'<div class="card"><h3>{f["title"]}</h3><p>{f["desc"]}</p></div>' for f in features])
                sections_html += f'<div class="grid">{cards}</div>'
            elif stype == 'text':
                sections_html += f'<div class="card"><h2>{section.get("title", "")}</h2><p>{section.get("text", "")}</p></div>'
            elif stype == 'stats':
                stats = section.get('items', [])
                stats_html = ''.join([f'<div style="text-align:center"><div style="font-size:2.5em;font-weight:bold;color:#00f0ff">{s["value"]}</div><div>{s["label"]}</div></div>' for s in stats])
                sections_html += f'<div class="card" style="display:flex;justify-content:space-around;flex-wrap:wrap">{stats_html}</div>'
        
        html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>{css}</style>
</head>
<body>
    <div class="container">
{sections_html}
    </div>
</body>
</html>'''
        return html
    
    def generate_landing_page(self, name, tagline, features, cta="Get Started"):
        """Generate a marketing landing page."""
        sections = [
            {"type": "hero", "title": name, "text": tagline, "cta": cta},
            {"type": "features", "items": [{"title": f[0], "desc": f[1]} for f in features]}
        ]
        return self.generate_html_page(f"{name} — {tagline}", sections, 'dark')
    
    def generate_web_app(self, name, components):
        """Generate a simple web app with JS interactivity."""
        html = self.generate_html_page(name, [], 'dark')
        
        # Add a simple JS console
        js = '''
    <script>
        console.log("[EMPIRE] App loaded");
        window.empire = {
            version: "1.0",
            log: (msg) => console.log("[APP] " + msg),
            alert: (msg) => alert(msg)
        };
    </script>
'''
        html = html.replace('</body>', f'{js}</body>')
        return html
    
    # ─── SELF-HEALING ───
    def fix_bare_excepts(self, path):
        """Fix bare except:pass patterns."""
        content = self.read_file(path)
        if not content:
            return {"error": "File not found"}
        
        fixed = re.sub(r'except:\s*\n\s*pass', 'except Exception as e:\n        print(f"Error: {e}")', content)
        if fixed != content:
            self.write_file(path, fixed)
            return {"status": "fixed", "path": path, "changes": "bare_excepts"}
        return {"status": "no_changes"}
    
    def add_error_handling(self, path):
        """Wrap functions with try/except."""
        content = self.read_file(path)
        if not content:
            return {"error": "File not found"}
        
        # Find functions without try blocks and wrap them
        pattern = r'(def\s+\w+\([^)]*\):\n)((?:\s+[^\n]*\n)+?)(?=\n\s*def|\Z)'
        
        def wrap_match(m):
            func_def = m.group(1)
            body = m.group(2)
            if 'try:' not in body:
                indented_body = '\n'.join(['    try:' + ('' if i == 0 else '    ' + line) 
                                           for i, line in enumerate(body.split('\n'))])
                return func_def + indented_body + '\n    except Exception as e:\n        print(f"Error: {e}")\n'
            return m.group(0)
        
        fixed = re.sub(pattern, wrap_match, content, flags=re.DOTALL)
        if fixed != content:
            self.write_file(path, fixed)
            return {"status": "enhanced", "path": path}
        return {"status": "no_changes"}
    
    # ─── AUTONOMOUS ACTIONS ───
    def analyze_project(self):
        """Analyze all files and report what needs work."""
        files = self.list_files(r'.*\.py$')
        report = {
            "files": [],
            "total_lines": 0,
            "total_functions": 0,
            "total_todos": 0,
            "total_fixmes": 0,
            "recommendations": []
        }
        
        for f in files:
            analysis = self.analyze_file(f)
            issues = self.find_issues(f)
            report["files"].append({"path": f, "analysis": analysis, "issues": issues})
            report["total_lines"] += analysis.get("lines", 0)
            report["total_functions"] += len(analysis.get("functions", []))
            report["total_todos"] += analysis.get("todo_count", 0)
            report["total_fixmes"] += analysis.get("fixme_count", 0)
        
        if report["total_todos"] > 0:
            report["recommendations"].append(f"Address {report['total_todos']} TODOs")
        if report["total_fixmes"] > 0:
            report["recommendations"].append(f"Fix {report['total_fixmes']} FIXMEs")
        if len(files) < 5:
            report["recommendations"].append("Project is small. Consider adding more modules.")
        
        return report
    
    def auto_fix(self):
        """Automatically fix common issues across project."""
        files = self.list_files(r'.*\.py$')
        results = []
        for f in files:
            r = self.fix_bare_excepts(f)
            if r.get("status") == "fixed":
                results.append(r)
        return {"fixed_files": results, "count": len(results)}
    
    def generate_module_for(self, purpose, functions_needed):
        """Generate a new module based on requirements."""
        name = purpose.lower().replace(' ', '_')
        funcs = []
        for func_name, desc in functions_needed:
            funcs.append((func_name, desc, [], ['pass']))
        
        code = self.generate_python_module(name, purpose, funcs)
        path = f"{name}.py"
        self.write_file(path, code)
        return {"status": "generated", "path": path, "purpose": purpose}


if __name__ == '__main__':
    coder = AutoCoder('~/liljr_autocode')
    print("[AUTOCODER] Ready to build. Run analyze_project() or generate_* methods.")
