#!/bin/bash
# quick_provider.sh — Get a cheap VPS and deploy LilJR in one shot
# If you don't have a server, this helps you get one

echo ""
echo "☁️ LILJR PROVIDER GUIDE"
echo "======================="
echo ""
echo "Your phone = Terminal. The cloud = LilJR's immortal brain."
echo "Even if your phone dies, the brain keeps running."
echo ""
echo "💰 CHEAPEST PROVIDERS (tested with LilJR):"
echo ""
echo "1. HETZNER CLOUD 🇩🇪 (Best value)"
echo "   Cost: ~$5/month (CPX11: 2 vCPU, 4GB RAM)"
echo "   Speed: Fastest in EU, good US"
echo "   Sign up: https://console.hetzner.cloud"
echo "   Create project → Add server → Ubuntu 22.04"
echo "   Copy the IP address"
echo ""
echo "2. DIGITALOCEAN 🇺🇸 (Easiest)"
echo "   Cost: ~$6/month (Basic: 1 vCPU, 1GB RAM)"
echo "   Speed: Good global"
echo "   Sign up: https://cloud.digitalocean.com"
echo "   Droplets → Create → Ubuntu 22.04"
echo "   Copy the IP address"
echo ""
echo "3. VULTR 🇺🇸 (Instant)"
echo "   Cost: ~$6/month (1 vCPU, 1GB RAM)"
echo "   Speed: 20+ locations"
echo "   Sign up: https://my.vultr.com"
echo "   Deploy → Cloud Compute → Ubuntu 22.04"
echo "   Copy the IP address"
echo ""
echo "4. RAILWAY ☁️ (Easiest, no server needed)"
echo "   Cost: ~$5/month (starter plan)"
echo "   Already have project: 39971d68-322a-40f5-ac8a-4a1f9f2771e5"
echo "   Command: npx @railway/cli up"
echo ""
echo "🚀 ONCE YOU HAVE THE IP, RUN:"
echo "   bash cloud_deploy.sh YOUR_SERVER_IP"
echo ""
echo "   Or if you have Railway:"
echo "   cd ~/liljr-autonomous && npx @railway/cli up"
echo ""
echo "📱 THEN ON YOUR PHONE:"
echo "   Open Chrome → http://YOUR_SERVER_IP"
echo "   Add to Home Screen → works from anywhere"
echo ""
echo "🛡️ WHAT THE CLOUD GIVES YOU:"
echo "   • Brain runs 24/7 (even phone off)"
echo "   • Public URL (access from any device)"
echo "   • Nginx proxy + SSL"
echo "   • Firewall + fail2ban"
echo "   • Systemd auto-restart"
echo "   • Tor anonymity ready"
echo ""
echo "Your phone just became a remote control for an immortal AI."
echo ""
